var SetFormHandlers=(function($){$(document).on('content-ready',function(e,element){var $contact_wrapper=$(element).find(".contact-fields"),request=window.location.href;window.button_text=$('#form_signup #submit').text();window.is_medium=(request.indexOf("referrer=")>=0&&request.indexOf("media")>=0&&request.indexOf("postId")>=0)?true:false;$(element).find("#form_video_cover").click(function(){$("#form_wrapper").css({'z-index':12,opacity:1});});if(!window.is_medium){$("#medium_opt_in").parent().remove();}
if($("body").is(".single-upscribe_form")){new Clipboard('.form-page-link-click');}
if($('.form-page-signups-count')){refresh_signups_count();}
$(".responsive-text").flowtype({maximum:725,minFont:14,maxFont:27,fontRatio:18,});if($('body').is('.as_embed')&&!$('body').is('.no-args')){$(window).on('touchmove scroll',function(e){e.preventDefault();window.scrollTo(0,0);});}
$("#form_signup").find("#submit").click(submit_subcriber);$("#form_signup").submit(function(e){if(window.is_medium)return false;submit_subcriber(e);return false;});$contact_wrapper.find('input').keyup(function(){$(this).removeClass('error-field');});});})(jQuery);var submit_subcriber=function(e){var $=jQuery,data=$("#form_signup").serialize(),title=$(".form-page-title .editable").text();if($("#email").length>0&&(!$("#email").val().length||!validate_email($("#email").val()))){$("#email").addClass('error-field').focus();show_notice('Is that your email?');return false;}
if(($("#opt_in").length&&!$("#opt_in").prop('checked'))||(window.is_medium&&$("#medium_opt_in").length&&!$("#medium_opt_in").prop('checked'))){show_notice('Please select the opt-in checkbox.');return false;}
$('.form-page a.button').html("<i class=\"ion-more\"></i>");if(window.is_medium){data=''+
'data='+encodeURIComponent(data)+
'&source='+encodeURIComponent(window.location.href)+
'&referrer='+encodeURIComponent(refData&&refData.referrer?refData.referrer:"")+
'&redirect=chyeah';var form_submit_url=window.location.origin+window.location.pathname+'?'+data;$("#form_signup").find("#submit").attr('href',form_submit_url);$(".form-page-title").text('Leaving Medium.com to subscribe...');$(".form-page-description").hide();$(".form-page-signups-count").hide();$(".form-page-form").hide();setTimeout(function(){$(".form-page-title").text(title);$(".form-page a.button").text(window.button_text);$(".form-page-description").show();$(".form-page-signups-count").show();$(".form-page-form").show();window.open(form_submit_url,'_blank');},1000);if($(window).width()<767){return true;}else{return false;}}
e.preventDefault();$.post(window.ajaxUrl,{action:"add_list_signup",data:data,source:window.location.href,referrer:refData&&refData.referrer?refData.referrer:"",},function(response){response=$.parseJSON(response);if(response.success!='1'){$('.contact-fields input').val('');show_notice(response.message||"Oops! Please try again.");return false;}
if(typeof ga!=="undefined"){ga('user.send','event','Upscribe Form','New Subscriber',window.location.origin+window.location.pathname);}
if(typeof fbq!=="undefined"){fbq('track','Lead');}
if(response.redirect){window.top.location.href=response.redirect;}
$(".form-page").fadeOut(300,function(){$("#form_video_cover").hide();$("#form_video").css({'z-index':13});$("#form_signup").hide();$(".form-page-image").hide();$(".form-page-description").hide();$(".form-page-signups-count").hide();$(".form-page-policy-links").hide();$(".form-page-title").hide();$(".form-page-confirmation").show().attr("style","");if(response.signupId){$("button[class*='_share']").each(function(){var share_url=$(this).data('url'),symbol='?';if(share_url.indexOf('?')>=0)symbol='&';$(this).data('url',share_url+symbol+response.signupId);});}
$(".form-page-share").show();$(".form-page-text").attr("style","");$(this).fadeIn(300,function(){$(".responsive-text").flowtype({maximum:725,minFont:14,maxFont:27,fontRatio:18,});});});return false;}).fail(function(data){console.log("error updating signup");console.log(data);});return false;}
var show_notice=function(message){var $=jQuery;$("#submit").text(message);setTimeout(function(){$("#submit").text(window.button_text);},2000);}
var refresh_signups_count=function(){var $=jQuery,$counter=$('.form-page-signups-count'),postId=$('#form_signup').find('input[name="form_id"]').val();if($counter.hasClass('loading-count'))
return false;$counter.addClass('loading-count');$.post(window.ajaxUrl,{action:'get_form_signups_count',post_id:postId},function(response){$counter.text(response+' signups');$counter.removeClass('loading-count');}).fail(function(data){console.log("error");console.log(data);});}
var validate_email=function(email){var re=/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;if(!email||email.trim()==''){return false;}
return re.test(email);}