var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,e,c){d!=Array.prototype&&d!=Object.prototype&&(d[e]=c.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var d=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+d++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(d){var e=0;return $jscomp.iteratorPrototype(function(){return e<d.length?{done:!1,value:d[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};$jscomp.makeIterator=function(d){$jscomp.initSymbolIterator();var e=d[Symbol.iterator];return e?e.call(d):$jscomp.arrayIterator(d)};
$jscomp.polyfill=function(d,e,c,h){if(e){c=$jscomp.global;d=d.split(".");for(h=0;h<d.length-1;h++){var g=d[h];g in c||(c[g]={});c=c[g]}d=d[d.length-1];h=c[d];e=e(h);e!=h&&null!=e&&$jscomp.defineProperty(c,d,{configurable:!0,writable:!0,value:e})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(d){function e(){this.batch_=null}function c(b){return b instanceof g?b:new g(function(a,k){a(b)})}if(d&&!$jscomp.FORCE_POLYFILL_PROMISE)return d;e.prototype.asyncExecute=function(b){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(b);return this};e.prototype.asyncExecuteBatch_=function(){var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})};var h=$jscomp.global.setTimeout;e.prototype.asyncExecuteFunction=function(b){h(b,
0)};e.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=this.batch_;this.batch_=[];for(var a=0;a<b.length;++a){var k=b[a];delete b[a];try{k()}catch(f){this.asyncThrow_(f)}}}this.batch_=null};e.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var g=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{b(a.resolve,a.reject)}catch(k){a.reject(k)}};g.prototype.createResolveAndReject_=
function(){function b(b){return function(f){k||(k=!0,b.call(a,f))}}var a=this,k=!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};g.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof g)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};g.prototype.resolveToNonPromiseObj_=function(b){var a=
void 0;try{a=b.then}catch(k){this.reject_(k);return}"function"==typeof a?this.settleSameAsThenable_(a,b):this.fulfill_(b)};g.prototype.reject_=function(b){this.settle_(2,b)};g.prototype.fulfill_=function(b){this.settle_(1,b)};g.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a|"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};g.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=
this.onSettledCallbacks_,a=0;a<b.length;++a)b[a].call(),b[a]=null;this.onSettledCallbacks_=null}};var l=new e;g.prototype.settleSameAsPromise_=function(b){var a=this.createResolveAndReject_();b.callWhenSettled_(a.resolve,a.reject)};g.prototype.settleSameAsThenable_=function(b,a){var k=this.createResolveAndReject_();try{b.call(a,k.resolve,k.reject)}catch(f){k.reject(f)}};g.prototype.then=function(b,a){function k(a,b){return"function"==typeof a?function(b){try{f(a(b))}catch(n){c(n)}}:b}var f,c,d=new g(function(a,
b){f=a;c=b});this.callWhenSettled_(k(b,f),k(a,c));return d};g.prototype.catch=function(b){return this.then(void 0,b)};g.prototype.callWhenSettled_=function(b,a){function k(){switch(f.state_){case 1:b(f.result_);break;case 2:a(f.result_);break;default:throw Error("Unexpected state: "+f.state_);}}var f=this;null==this.onSettledCallbacks_?l.asyncExecute(k):this.onSettledCallbacks_.push(function(){l.asyncExecute(k)})};g.resolve=c;g.reject=function(b){return new g(function(a,k){k(b)})};g.race=function(b){return new g(function(a,
k){for(var f=$jscomp.makeIterator(b),d=f.next();!d.done;d=f.next())c(d.value).callWhenSettled_(a,k)})};g.all=function(b){var a=$jscomp.makeIterator(b),k=a.next();return k.done?c([]):new g(function(b,d){function f(a){return function(f){e[a]=f;z--;0==z&&b(e)}}var e=[],z=0;do e.push(void 0),z++,c(k.value).callWhenSettled_(f(e.length-1),d),k=a.next();while(!k.done)})};return g},"es6","es3");$jscomp.owns=function(d,e){return Object.prototype.hasOwnProperty.call(d,e)};
$jscomp.polyfill("WeakMap",function(d){function e(b){$jscomp.owns(b,h)||$jscomp.defineProperty(b,h,{value:{}})}function c(b){var a=Object[b];a&&(Object[b]=function(b){e(b);return a(b)})}if(function(){if(!d||!Object.seal)return!1;try{var b=Object.seal({}),a=Object.seal({}),c=new d([[b,2],[a,3]]);if(2!=c.get(b)||3!=c.get(a))return!1;c.delete(b);c.set(a,4);return!c.has(b)&&4==c.get(a)}catch(f){return!1}}())return d;var h="$jscomp_hidden_"+Math.random().toString().substring(2);c("freeze");c("preventExtensions");
c("seal");var g=0,l=function(b){this.id_=(g+=Math.random()+1).toString();if(b){$jscomp.initSymbol();$jscomp.initSymbolIterator();b=$jscomp.makeIterator(b);for(var a;!(a=b.next()).done;)a=a.value,this.set(a[0],a[1])}};l.prototype.set=function(b,a){e(b);if(!$jscomp.owns(b,h))throw Error("WeakMap key fail: "+b);b[h][this.id_]=a;return this};l.prototype.get=function(b){return $jscomp.owns(b,h)?b[h][this.id_]:void 0};l.prototype.has=function(b){return $jscomp.owns(b,h)&&$jscomp.owns(b[h],this.id_)};l.prototype.delete=
function(b){return $jscomp.owns(b,h)&&$jscomp.owns(b[h],this.id_)?delete b[h][this.id_]:!1};return l},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(d){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!d||!d.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),b=new d($jscomp.makeIterator([[a,"s"]]));if("s"!=b.get(a)||1!=b.size||b.get({x:4})||b.set({x:4},"t")!=b||2!=b.size)return!1;var f=b.entries(),c=f.next();if(c.done||c.value[0]!=a||"s"!=c.value[1])return!1;c=f.next();return c.done||4!=c.value[0].x||"t"!=c.value[1]||!f.next().done?!1:!0}catch(t){return!1}}())return d;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var e=new WeakMap,c=function(a){this.data_={};this.head_=l();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};c.prototype.set=function(a,b){var f=h(this,a);f.list||(f.list=this.data_[f.id]=[]);f.entry?f.entry.value=b:(f.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:b},f.list.push(f.entry),this.head_.previous.next=f.entry,this.head_.previous=f.entry,this.size++);return this};c.prototype.delete=
function(a){a=h(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=l();this.size=0};c.prototype.has=function(a){return!!h(this,a).entry};c.prototype.get=function(a){return(a=h(this,a).entry)&&a.value};c.prototype.entries=function(){return g(this,function(a){return[a.key,
a.value]})};c.prototype.keys=function(){return g(this,function(a){return a.key})};c.prototype.values=function(){return g(this,function(a){return a.value})};c.prototype.forEach=function(a,b){for(var f=this.entries(),c;!(c=f.next()).done;)c=c.value,a.call(b,c[1],c[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var h=function(a,c){var f=c&&typeof c;"object"==f||"function"==f?e.has(c)?f=e.get(c):(f=""+ ++b,e.set(c,f)):f="p_"+c;var d=a.data_[f];if(d&&$jscomp.owns(a.data_,f))for(a=0;a<d.length;a++){var h=
d[a];if(c!==c&&h.key!==h.key||c===h.key)return{id:f,list:d,index:a,entry:h}}return{id:f,list:d,index:-1,entry:void 0}},g=function(b,c){var a=b.head_;return $jscomp.iteratorPrototype(function(){if(a){for(;a.head!=b.head_;)a=a.previous;for(;a.next!=a.head;)return a=a.next,{done:!1,value:c(a)};a=null}return{done:!0,value:void 0}})},l=function(){var a={};return a.previous=a.next=a.head=a},b=0;return c},"es6","es3");
$jscomp.polyfill("Set",function(d){if(!$jscomp.ASSUME_NO_NATIVE_SET&&function(){if(!d||!d.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),e=new d($jscomp.makeIterator([c]));if(!e.has(c)||1!=e.size||e.add(c)!=e||1!=e.size||e.add({x:4})!=e||2!=e.size)return!1;var g=e.entries(),l=g.next();if(l.done||l.value[0]!=c||l.value[1]!=c)return!1;l=g.next();return l.done||l.value[0]==c||4!=l.value[0].x||l.value[1]!=l.value[0]?!1:g.next().done}catch(b){return!1}}())return d;
$jscomp.initSymbol();$jscomp.initSymbolIterator();var e=function(c){this.map_=new Map;if(c){c=$jscomp.makeIterator(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.map_.size};e.prototype.add=function(c){this.map_.set(c,c);this.size=this.map_.size;return this};e.prototype.delete=function(c){c=this.map_.delete(c);this.size=this.map_.size;return c};e.prototype.clear=function(){this.map_.clear();this.size=0};e.prototype.has=function(c){return this.map_.has(c)};e.prototype.entries=function(){return this.map_.entries()};
e.prototype.values=function(){return this.map_.values()};e.prototype.keys=e.prototype.values;e.prototype[Symbol.iterator]=e.prototype.values;e.prototype.forEach=function(c,d){var e=this;this.map_.forEach(function(g){return c.call(d,g,g,e)})};return e},"es6","es3");
$jscomp.polyfill("Array.from",function(d){return d?d:function(d,c,h){$jscomp.initSymbolIterator();c=null!=c?c:function(a){return a};var e=[],l=d[Symbol.iterator];if("function"==typeof l)for(d=l.call(d);!(l=d.next()).done;)e.push(c.call(h,l.value));else{l=d.length;for(var b=0;b<l;b++)e.push(c.call(h,d[b]))}return e}},"es6","es3");
(function(){function d(a,b){return b={exports:{}},a(b,b.exports),b.exports}function e(a,b){return Array.prototype.slice.call((b||document).querySelectorAll(a))}function c(a){return e(k.join(","),a).filter(function(a){return!!(a.offsetWidth||a.offsetHeight||a.getClientRects().length)})}function h(){try{return document.activeElement}catch(f){}}function g(a,b,d,e){a&&27===e.which&&(e.preventDefault(),b());if(a&&9===e.which){a=c(d);var f;0<a.length&&(b=a.indexOf(h()),e.shiftKey&&0===b?f=a[a.length-1]:
e.shiftKey||b!==a.length-1||(f=a[0]));f&&(f.focus(),e.preventDefault())}}function l(a){var b;(b=c(a)[0])||(b=document.createElement("div"),b.setAttribute("tabindex","0"),b.style.cssText="outline:none;",a.insertBefore(b,a.firstChild));(a=b)&&a.focus()}var b="undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:{},a=d(function(a){(function(){function b(a,b){document.addEventListener?a.addEventListener("scroll",b,!1):a.attachEvent("scroll",b)}function c(a){document.body?
a():document.addEventListener?document.addEventListener("DOMContentLoaded",function E(){document.removeEventListener("DOMContentLoaded",E);a()}):document.attachEvent("onreadystatechange",function F(){if("interactive"==document.readyState||"complete"==document.readyState)document.detachEvent("onreadystatechange",F),a()})}function d(a){this.a=document.createElement("div");this.a.setAttribute("aria-hidden","true");this.a.appendChild(document.createTextNode(a));this.b=document.createElement("span");this.c=
document.createElement("span");this.h=document.createElement("span");this.f=document.createElement("span");this.g=-1;this.b.style.cssText="max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";this.c.style.cssText="max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";this.f.style.cssText="max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";
this.h.style.cssText="display:inline-block;width:200%;height:200%;font-size:16px;max-width:none;";this.b.appendChild(this.h);this.c.appendChild(this.f);this.a.appendChild(this.b);this.a.appendChild(this.c)}function e(a,b){a.a.style.cssText="max-width:none;min-width:20px;min-height:20px;display:inline-block;overflow:hidden;position:absolute;width:auto;margin:0;padding:0;top:-999px;white-space:nowrap;font-synthesis:none;font:"+b+";"}function f(a){var b=a.a.offsetWidth,m=b+100;a.f.style.width=m+"px";
a.c.scrollLeft=m;a.b.scrollLeft=a.b.scrollWidth+100;return a.g!==b?(a.g=b,!0):!1}function g(a,m){function c(){var a=d;f(a)&&a.a.parentNode&&m(a.g)}var d=a;b(a.b,c);b(a.c,c);f(a)}function h(a,b){b=b||{};this.family=a;this.style=b.style||"normal";this.weight=b.weight||"normal";this.stretch=b.stretch||"normal"}function l(){if(null===x)if(k()&&/Apple/.test(window.navigator.vendor)){var a=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))(?:\.([0-9]+))/.exec(window.navigator.userAgent);x=!!a&&603>parseInt(a[1],10)}else x=
!1;return x}function k(){null===q&&(q=!!document.fonts);return q}function y(){if(null===A){var a=document.createElement("div");try{a.style.font="condensed 100px sans-serif"}catch(G){}A=""!==a.style.font}return A}function m(a,b){return[a.style,a.weight,y()?a.stretch:"","100px",b].join(" ")}var C=null,x=null,A=null,q=null;h.prototype.load=function(a,b){var f=this,x=a||"BESbswy",y=0,h=b||3E3,A=(new Date).getTime();return new Promise(function(a,b){if(k()&&!l()){var n=new Promise(function(a,b){function c(){(new Date).getTime()-
A>=h?b():document.fonts.load(m(f,'"'+f.family+'"'),x).then(function(b){1<=b.length?a():setTimeout(c,25)},function(){b()})}c()}),q=new Promise(function(a,b){y=setTimeout(b,h)});Promise.race([q,n]).then(function(){clearTimeout(y);a(f)},function(){b(f)})}else c(function(){function c(){var b;if(b=-1!=v&&-1!=t||-1!=v&&-1!=w||-1!=t&&-1!=w)(b=v!=t&&v!=w&&t!=w)||(null===C&&(b=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))/.exec(window.navigator.userAgent),C=!!b&&(536>parseInt(b[1],10)||536===parseInt(b[1],10)&&11>=
parseInt(b[2],10))),b=C&&(v==p&&t==p&&w==p||v==z&&t==z&&w==z||v==u&&t==u&&w==u)),b=!b;b&&(r.parentNode&&r.parentNode.removeChild(r),clearTimeout(y),a(f))}function k(){if((new Date).getTime()-A>=h)r.parentNode&&r.parentNode.removeChild(r),b(f);else{var a=document.hidden;if(!0===a||void 0===a)v=l.a.offsetWidth,t=n.a.offsetWidth,w=q.a.offsetWidth,c();y=setTimeout(k,50)}}var l=new d(x),n=new d(x),q=new d(x),v=-1,t=-1,w=-1,p=-1,z=-1,u=-1,r=document.createElement("div");r.dir="ltr";e(l,m(f,"sans-serif"));
e(n,m(f,"serif"));e(q,m(f,"monospace"));r.appendChild(l.a);r.appendChild(n.a);r.appendChild(q.a);document.body.appendChild(r);p=l.a.offsetWidth;z=n.a.offsetWidth;u=q.a.offsetWidth;k();g(l,function(a){v=a;c()});e(l,m(f,'"'+f.family+'",sans-serif'));g(n,function(a){t=a;c()});e(n,m(f,'"'+f.family+'",serif'));g(q,function(a){w=a;c()});e(q,m(f,'"'+f.family+'",monospace'))})})};a.exports=h})()}),k='a[href] area[href] input:not([disabled]) select:not([disabled]) textarea:not([disabled]) button:not([disabled]) iframe object embed [contenteditable] [tabindex]:not([tabindex^\x3d"-"])'.split(" ");
d(function(a,c){(function(a,b){b()})(b,function(){function a(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");}function b(a,m,c){if(a.nodeType==Node.ELEMENT_NODE){m&&m(a);var d=a.shadowRoot||a.webkitShadowRoot;if(d){b(d,m,d);return}if("content"==a.localName){a=a.getDistributedNodes?a.getDistributedNodes():[];for(d=0;d<a.length;d++)b(a[d],m,c);return}if("slot"==a.localName){a=a.assignedNodes?a.assignedNodes({flatten:!0}):[];for(d=0;d<a.length;d++)b(a[d],m,c);return}}for(a=
a.firstChild;null!=a;)b(a,m,c),a=a.nextSibling}function c(a){if(!a.querySelector("style#inert-style")){var b=document.createElement("style");b.setAttribute("id","inert-style");b.textContent="\n[inert] {\n  pointer-events: none;\n  cursor: default;\n}\n\n[inert], [inert] * {\n  user-select: none;\n  -webkit-user-select: none;\n  -moz-user-select: none;\n  -ms-user-select: none;\n}\n";a.appendChild(b)}}var d=function(){function a(a,b){for(var m=0;m<b.length;m++){var c=b[m];c.enumerable=c.enumerable||
!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(a,c.key,c)}}return function(b,c,d){c&&a(b.prototype,c);d&&a(b,d);return b}}(),e=Array.prototype.slice,f=function(){function c(b,d){a(this,c);this._inertManager=d;this._rootElement=b;this._managedNodes=new Set([]);this._rootElement.hasAttribute("aria-hidden")&&(this._savedAriaHidden=this._rootElement.getAttribute("aria-hidden"));this._rootElement.setAttribute("aria-hidden","true");this._makeSubtreeUnfocusable(this._rootElement);
this._observer=new MutationObserver(this._onMutation.bind(this));this._observer.observe(this._rootElement,{attributes:!0,childList:!0,subtree:!0})}d(c,[{key:"destructor",value:function(){this._observer.disconnect();this._observer=null;this._rootElement&&(this.hasSavedAriaHidden?this._rootElement.setAttribute("aria-hidden",this.savedAriaHidden):this._rootElement.removeAttribute("aria-hidden"));this._rootElement=null;this._managedNodes.forEach(function(a){this._unmanageNode(a.node)},this);this._inertManager=
this._managedNodes=null}},{key:"_makeSubtreeUnfocusable",value:function(a){var c=this;b(a,function(a){return c._visitNode(a)});var m=document.activeElement;if(!document.body.contains(a)){for(var d=a,e=void 0;d;){if(d.nodeType===Node.DOCUMENT_FRAGMENT_NODE){e=d;break}d=d.parentNode}e&&(m=e.activeElement)}a.contains(m)&&(m.blur(),m===document.activeElement&&document.body.focus())}},{key:"_visitNode",value:function(a){a.nodeType===Node.ELEMENT_NODE&&(a!==this._rootElement&&a.hasAttribute("inert")&&this._adoptInertRoot(a),
(a.matches("a[href],area[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),button:not([disabled]),iframe,object,embed,[contenteditable]")||a.hasAttribute("tabindex"))&&this._manageNode(a))}},{key:"_manageNode",value:function(a){a=this._inertManager.register(a,this);this._managedNodes.add(a)}},{key:"_unmanageNode",value:function(a){(a=this._inertManager.deregister(a,this))&&this._managedNodes.delete(a)}},{key:"_unmanageSubtree",value:function(a){var c=this;b(a,function(a){return c._unmanageNode(a)})}},
{key:"_adoptInertRoot",value:function(a){var b=this._inertManager.getInertRoot(a);b||(this._inertManager.setInert(a,!0),b=this._inertManager.getInertRoot(a));b.managedNodes.forEach(function(a){this._manageNode(a.node)},this)}},{key:"_onMutation",value:function(a,b){a.forEach(function(a){var b=a.target;if("childList"===a.type)e.call(a.addedNodes).forEach(function(a){this._makeSubtreeUnfocusable(a)},this),e.call(a.removedNodes).forEach(function(a){this._unmanageSubtree(a)},this);else if("attributes"===
a.type)if("tabindex"===a.attributeName)this._manageNode(b);else if(b!==this._rootElement&&"inert"===a.attributeName&&b.hasAttribute("inert")){this._adoptInertRoot(b);var c=this._inertManager.getInertRoot(b);this._managedNodes.forEach(function(a){b.contains(a.node)&&c._manageNode(a.node)})}},this)}},{key:"managedNodes",get:function(){return new Set(this._managedNodes)}},{key:"hasSavedAriaHidden",get:function(){return"_savedAriaHidden"in this}},{key:"savedAriaHidden",set:function(a){this._savedAriaHidden=
a},get:function(){return this._savedAriaHidden}}]);return c}(),g=function(){function b(c,d){a(this,b);this._node=c;this._overrodeFocusMethod=!1;this._inertRoots=new Set([d]);this._destroyed=!1;this.ensureUntabbable()}d(b,[{key:"destructor",value:function(){this._throwIfDestroyed();this._node&&(this.hasSavedTabIndex?this._node.setAttribute("tabindex",this.savedTabIndex):this._node.removeAttribute("tabindex"),this._overrodeFocusMethod&&delete this._node.focus);this._inertRoots=this._node=null;this._destroyed=
!0}},{key:"_throwIfDestroyed",value:function(){if(this.destroyed)throw Error("Trying to access destroyed InertNode");}},{key:"ensureUntabbable",value:function(){var a=this.node;a.matches("a[href],area[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),button:not([disabled]),iframe,object,embed,[contenteditable]")?-1===a.tabIndex&&this.hasSavedTabIndex||(a.hasAttribute("tabindex")&&(this._savedTabIndex=a.tabIndex),a.setAttribute("tabindex","-1"),a.nodeType===Node.ELEMENT_NODE&&
(a.focus=function(){},this._overrodeFocusMethod=!0)):a.hasAttribute("tabindex")&&(this._savedTabIndex=a.tabIndex,a.removeAttribute("tabindex"))}},{key:"addInertRoot",value:function(a){this._throwIfDestroyed();this._inertRoots.add(a)}},{key:"removeInertRoot",value:function(a){this._throwIfDestroyed();this._inertRoots.delete(a);0===this._inertRoots.size&&this.destructor()}},{key:"destroyed",get:function(){return this._destroyed}},{key:"hasSavedTabIndex",get:function(){return"_savedTabIndex"in this}},
{key:"node",get:function(){this._throwIfDestroyed();return this._node}},{key:"savedTabIndex",set:function(a){this._throwIfDestroyed();this._savedTabIndex=a},get:function(){this._throwIfDestroyed();return this._savedTabIndex}}]);return b}(),h=new (function(){function b(d){a(this,b);if(!d)throw Error("Missing required argument; InertManager needs to wrap a document.");this._document=d;this._managedNodes=new Map;this._inertRoots=new Map;this._observer=new MutationObserver(this._watchForInert.bind(this));
c(d.head||d.body||d.documentElement);"loading"===d.readyState?d.addEventListener("DOMContentLoaded",this._onDocumentLoaded.bind(this)):this._onDocumentLoaded()}d(b,[{key:"setInert",value:function(a,b){if(b){if(!this._inertRoots.has(a)&&(b=new f(a,this),a.setAttribute("inert",""),this._inertRoots.set(a,b),!this._document.body.contains(a)))for(a=a.parentNode;a;)11===a.nodeType&&c(a),a=a.parentNode}else this._inertRoots.has(a)&&(this._inertRoots.get(a).destructor(),this._inertRoots.delete(a),a.removeAttribute("inert"))}},
{key:"getInertRoot",value:function(a){return this._inertRoots.get(a)}},{key:"register",value:function(a,b){var c=this._managedNodes.get(a);void 0!==c?(c.addInertRoot(b),c.ensureUntabbable()):c=new g(a,b);this._managedNodes.set(a,c);return c}},{key:"deregister",value:function(a,b){var c=this._managedNodes.get(a);if(!c)return null;c.removeInertRoot(b);c.destroyed&&this._managedNodes.delete(a);return c}},{key:"_onDocumentLoaded",value:function(){e.call(this._document.querySelectorAll("[inert]")).forEach(function(a){this.setInert(a,
!0)},this);this._observer.observe(this._document.body,{attributes:!0,subtree:!0,childList:!0})}},{key:"_watchForInert",value:function(a,b){a.forEach(function(a){switch(a.type){case "childList":e.call(a.addedNodes).forEach(function(a){if(a.nodeType===Node.ELEMENT_NODE){var b=e.call(a.querySelectorAll("[inert]"));a.matches("[inert]")&&b.unshift(a);b.forEach(function(a){this.setInert(a,!0)},this)}},this);break;case "attributes":if("inert"===a.attributeName){a=a.target;var b=a.hasAttribute("inert");this.setInert(a,
b)}}},this)}}]);return b}())(document);Object.defineProperty(Element.prototype,"inert",{enumerable:!0,get:function(){return this.hasAttribute("inert")},set:function(a){h.setInert(this,a)}})})});(function(){function a(a){g(!0,function(){d()},u,a)}function b(a){u.contains(a.target)||l(u)}function d(){document.removeEventListener("keydown",a);document.body.removeEventListener("focus",b,!0);var d=c(u);if(0<d.length){var e=d.indexOf(h());-1!==e&&d[e].blur()}y.focus()}function e(a){Array.from(document.body.children).forEach(function(b){b!==
D&&(b.inert=a,console.log(a))})}function k(c){"true"===c?(p.setAttribute("aria-hidden",!1),p.hidden=!1,y=h(),l(u),document.addEventListener("keydown",a),document.body.addEventListener("focus",b,!0),e(!0)):(setTimeout(function(){p.setAttribute("aria-hidden",!0);p.hidden=!0},450),d(),e(!1));n.setAttribute("aria-expanded",c);document.body.setAttribute("data-menu-expanded",c)}var D=document.querySelector(".c-menu");setTimeout(function(){D.classList.remove("no-transition")},10);var n=document.querySelector(".c-menu__button");
n.setAttribute("aria-expanded",!1);var p=document.querySelector(".c-menu__drawer");p.setAttribute("role","dialog");p.setAttribute("aria-hidden","true");p.hidden=!0;var B=document.createElement("div");document.body.appendChild(B);B.className="c-backdrop";B.setAttribute("tabindex",-1);document.body.setAttribute("data-menu-expanded",!1);var u=p,y;n&&(p.style.display="",document.querySelector(".c-menu__onload").remove(),n.addEventListener("click",function(a){var b="false"===n.getAttribute("aria-expanded")?
"true":"false";k(b);a.preventDefault()}),window.addEventListener("keyup",function(a){27===a.keyCode&&(k(!1),d())}),B.addEventListener("click",function(a){var b="false"===n.getAttribute("aria-expanded")?"true":"false";k(b);a.preventDefault()}))})();(function(){function b(){document.documentElement.classList.add("fonts-loaded");sessionStorage["fonts-loaded"]=!0}var c=[(new a("Source Sans Pro",{weight:"normal",style:"normal"})).load(),(new a("Source Sans Pro",{weight:"700",style:"normal"})).load(),(new a("Source Serif Pro",
{weight:"normal",style:"normal"})).load(),(new a("Source Code Pro",{weight:"normal",style:"normal"})).load()];(function(){Promise.all(c).then(b).catch(function(a){console.error(a)})})()})()})();
//# sourceMappingURL=app.js.map
